development:
  adapter: mysql2
  encoding: utf8
  database: digester
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: test_digester
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: digester
  username: root
  password: my_password
  host: 127.0.0.1
  port: 3306